# Generated by Django 4.0.6 on 2025-02-19 14:32

import calculator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tckn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('account_opening_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_calculated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=calculator.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tckn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('account_opening_date', models.DateTimeField(blank=True, null=True)),
                ('portfolio_date', models.DateTimeField(blank=True, null=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.calculator')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=10, max_digits=22)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=22)),
                ('transaction_fee', models.DecimalField(decimal_places=10, max_digits=22)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=22)),
                ('transaction_status', models.CharField(max_length=200)),
                ('transaction_currency', models.CharField(max_length=200)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.calculatorpdf')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
