# Generated by Django 4.0.6 on 2025-02-08 11:06

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='calculatorpdf',
            name='pdf',
            field=models.FileField(upload_to=calculator.models.get_upload_path),
        ),
    ]
