# Generated by Django 4.0.6 on 2025-02-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=14, max_digits=28),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=14, max_digits=28),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, max_digits=28),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=14, max_digits=28),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=14, max_digits=28)),
                ('buy_price', models.DecimalField(decimal_places=14, max_digits=28)),
                ('profit', models.DecimalField(decimal_places=14, max_digits=28)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.calculatorpdf')),
            ],
        ),
    ]
