# Generated by Django 4.0.6 on 2025-02-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calculator_id_alter_calculatorpdf_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorpdf',
            name='account_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatorpdf',
            name='portfolio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatorpdf',
            name='portfolio_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
