# Generated by Django 4.0.6 on 2025-02-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_calculatorpdf_account_info_calculatorpdf_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorpdf',
            name='account_info',
        ),
        migrations.AddField(
            model_name='calculatorpdf',
            name='account_opening_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatorpdf',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calculatorpdf',
            name='tckn',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
