# Generated by Django 4.0.6 on 2025-02-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_calculator_account_opening_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorpdf',
            name='transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
